### PR TITLE
Limit boiler output power and add minimum heat required power

### PR DESCRIPTION
**Pull request by lexyan**
Hi Philippe,

First I want to say thank you for this amazing work.
I managed to setup my Frisquet boiler with this and it's working great, No more over/under heat, temperature is extremely stable in my main room.

For personnal use I need to limit the output power of the boiler (low temperature radiator).
The minimum output power is not enough at minimum power to heat other room in my house (or it's extremely long to reach desired temperature)

So I added the 2 parameters configurable.

### CODE REVIEW

**Comment by philippemezzadri** [comment]
Hi @lexyan,

Thank you for your message and for your contribution to this project.

Before merging your pull request, I'd like to gain a better understanding of your use case.

1. I see the necessity of capping the boiler output. However, have you considered utilizing the `max_power` option of the `frisquet_boiler` output component? Internally, the `float_output` component performs a similar conversion using the following logic:
    ```c++
    state = (state * (this->max_power_ - this->min_power_)) + this->min_power_;
    ```
    I believe this approach could achieve the desired outcome, although it would require a review of the `output_factor` and `output_offset` accordingly.

2. Regarding the `heat_required_output` parameter you added, it appears to duplicate the functionality of `minimum_output`. Perhaps there's a reason for this that I'm overlooking. I encountered a similar issue at home, which led me to introduce this option and the `Heat Required` switch.

Philippe

**Comment by lexyan** [comment]
Hi,

For first point, I am new to esphome (I started with this project). I haven't check the float_output component before :( 
As we define `minimum_output` in the `heat_curve_climate` component I think it's better to define `maximum_output` next to it.
And as you state, it doesn't required touching `output_factor` and `output_offset` parameters. 
I also prefer to let `friquet_boiler` only managing the communication with the boiler and let the `climate` doing water temp calculation.

For point 2, at first glance it seems duplicate with `minimum_output`, in my house the climate is in my living room and with default parameters (`minimum_output` set to 10%) it works great with temperature stable at 0.2°C.
My settings are :
 ```
minimum_output: 0.1
maximum_output: 0.6
heat_required_output: 0.2
```
I use the `heat_required` switch to heat the bathroom, I test many settings and I need minimum 20% power to heat it (at 10% I can't reach the desired temperature), if I set the minimum_output to 20% my living room stopped heating when computed power is lower than 20% but it's not enough to maintain stable temperature in the living room. So I need a minimum_power at 20% to heat the bathroom but let the power down to 10% to maintain temperature in the living room stable.

Alexandre

**Comment by philippemezzadri** [comment]
Understood. I'll have a look at this next weekend.
Philippe

**Comment by philippemezzadri** [comment]
Hi again, 

looking at your code, I propose the following instead in `heat_curve_climate.cpp`:

```c++
  // shutdown boiler if outdoor temperature is too high or output below minimum value
  if (this->outdoor_temp_ > this->target_temperature - 2 || output < this->minimum_output_) {
    ESP_LOGD(TAG, "Forcing IDLE");
    output = 0;
  }

  // if heat required by switch, minimum output is heat_required_output_
  if (this->heat_required_ && output < this->heat_required_output_) {
    ESP_LOGD(TAG, "Forcing heat required minimum output");
    output = this->heat_required_output_;
  }
```
What do you think ?

**Comment by philippemezzadri** [comment]
Proposed modification included in main.
I did not include your yaml file proposed modification (web server, api, etc.) as this is personal to each user.

**Comment by lexyan** [comment]
Hi Philippe,
Sorry for the late reply, 
Your code is more clearer than mine so I totally agree.

For the yaml modification, you're right, I forgot to switch branch when doing my modifications.

**Pull request closed without merging**
